file_storage:
  service_name: 'pmil'
  host: '192.168.0.1'
  port: 139

logging:
  asr_path: 'C:\Users\PMIL\Documents\Dimos\ICMI\DATA\asr'
  #asr_path: 'C:\Users\kalins\Documents\Data\multisensoryprocessing\asr'
  sensor_path: 'C:\Users\PMIL\Documents\Dimos\ICMI\DATA\sensors'
  #sensor_path: 'C:\Users\kalins\Documents\Data\multisensoryprocessing\sensors'
  processor_path: 'C:\Users\PMIL\Documents\Dimos\ICMI\DATA\processors'
  #processor_path: 'C:\Users\kalins\Documents\Data\multisensoryprocessing\processors'

messaging:
  broker_host: "130.237.67.186"
  broker_port: 5672
  broker_user: "test"
  broker_pass: "test"

  # time server host
  time_server_host: "tcp://130.237.67.186:45321"

  # connection server
  connection_server_host: "tcp://130.237.67.186:45322"

  # sensor hosts
  mocap_host: "130.237.67.186"

  # furhat host
  furhat_host: "130.237.67.172"

  # exchanges
  artificial_agent: "artificial-agent"
  sensors: "sensors"
  pre_processing: "pre-processor"
  processing: "processor"

  # sensors
  microphone: "microphone"
  mocap: "mocap"
  tobii: "tobii"

  # new sensor
  new_sensor_mocap: "mocap.new_sensor.all"
  new_sensor_tobii: "tobii.new_sensor"
  new_sensor_mic: "mic.new_sensor.all"

  # pre_processing
  mocap_processing: "mocap.processing"
  tobii_processing: "tobii.processing"
  asr_processing: "asr.processing"

  #processors
  mocaptobii_processing: "mocaptobii.processing"
  feature_processing: "feature.processing"
  nlp_data: "nlp.data"
  asr_watson: "asr.data"
