file_storage:
  service_name: 'pmil'
  host: '192.168.0.1'
  port: 139

logging:
  asr_path: 'C:\Users\PMIL\Documents\Dimos\CHI\DATA\asr'
  sensor_path: 'C:\Users\PMIL\Documents\Dimos\CHI\DATA\sensors'
  processor_path: 'C:\Users\PMIL\Documents\Dimos\CHI\DATA\processors'

messaging:
  #broker_host: "192.168.1.136"
  broker_host: "130.237.67.194"
  broker_port: 5672
  broker_user: "test"
  broker_pass: "test"

  # time server host
  #time_server_host: "tcp://192.168.1.136:45321"
  time_server_host: "tcp://130.237.67.194:45321"

  # connection server
  #connection_server_host: "tcp://192.168.1.136:45322"
  connection_server_host: "tcp://130.237.67.194:45322"

  # sensor hosts
  mocap_host: "172.18.133.161"

  # furhat host
  #furhat_host: "192.168.1.133"
  furhat_host: "130.237.67.157"

  # exchanges
  artificial_agent: "artificial-agent"
  sensors: "sensors"
  pre_processing: "pre-processor"
  processing: "processor"

  # sensors
  microphone: "microphone"
  mocap: "mocap"
  tobii: "tobii"

  # new sensor
  new_sensor_mocap: "mocap.new_sensor.all"
  new_sensor_tobii: "tobii.new_sensor"
  new_sensor_mic: "mic.new_sensor.all"

  # pre_processing
  mocap_processing: "mocap.processing"
  tobii_processing: "tobii.processing"
  asr_processing: "asr.processing"

  #processors
  mocaptobii_processing: "mocaptobii.processing"
  feature_processing: "feature.processing"
  furhat_processing: "furhat.processing"
  nlp_data: "nlp.data"
  asr_watson: "asr.data"
  wizard_data: "wizard.data"
